### ISSUE TITLE
Bundlephobia Badge Error

### ISSUE THREAD

**Issue by Snipey** [pulse-framework/pulse#43] opened 2019-10-02 23:06 UTC
![Image of error](https://i.snipey.dev/u/16.04.38-02.10.19.png)

**Comment by twigeee** [comment] 2019-10-20 03:27
Caused by the Bundlephobia badge URL ending in `pulse-framework` when it should just be `pulse`. Fixed and included in my pull-request #46

**Comment by ipiv** [comment] 2020-01-04 23:17
fixed in #58 , can be marked closed

**Closed** 2020-08-12 06:08 UTC
